### ISSUE TITLE
Line ending issue on Windows.

### ISSUE THREAD

**Issue by sbelzile-Coveo** [coveo/pretty-typescript#24]
When running this on windows, line-ending of all files is changed from "\n" to "\r\n".

**Comment by olamothe** [comment]
Humm, it seems configured correctly here to always force \n: 

https://github.com/coveo/pretty-typescript/blob/master/tsfmt.json

Not sure why it's not working.

Have you been able to investigate the issue a bit ?

**Comment by tedre191** [comment]
This is an issue with your git configuration.
To fix this, you will need to change the `core.autocrlf` git setting to `input`.

https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#__code_core_autocrlf_code

You will most likely need to delete your repository and clone it again to apply this change.

**Comment by sbelzile-Coveo** [comment]
Thanks André, it actually fixed the problem.
